config/routes.rb
DesignUnited::Application.routes.draw do
  get "passwordreset/create"

  get "passwordreset/edit"

  get "passwordreset/update"

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"

  get "blogpages/index"

  get "home/index"

  get "pages/index"
  
  match "about", :controller => "abouts", :action => "show", :id => "1", :as => "aboutdu"
  match "introduction", :controller => "abouts", :action => "show", :id => "2", :as => "introduction"
  match "mission", :controller => "abouts", :action => "show", :id => "3", :as => "mission"
  match "activities", :controller => "abouts", :action => "show", :id => "4", :as => "activities"
  match "contact", :controller => "abouts", :action => "show", :id => "5", :as => "contact"
  
  root :to => "home#index"
  
  match "/pages" => "pages#index" #for search

  resources :abouts
  resources :profiles, :cases, :events, :users, :sessions, :passwordresets
  resources :blogpages do
    resources :comments
  end
  resources :users do
    member do
      get :activate
    end
  end


  
end

app/models/event.rb
class Event < Page
  validates_uniqueness_of :navigation_link
  
  scope :present, where("end_date IS NULL OR end_date > \"#{Time.now - 1.day}\"")
  scope :passed, where("end_date IS NOT NULL OR end_date <= \"#{Time.now - 1.day}\"")
  
  def to_param
    navigation_link
  end
end

app/controllers/events_controller.rb
class EventsController < InheritedResources::Base
    #load_and_authorize_resource

    def index
      @events = Event.order("date DESC")
      @events.each do |event|
        if event.end_date && event.end_date <= Time.now - 1.day
          event.archived = 1;
          event.save
        end
      end
      @new_events = Event.present.order("date DESC")
      @old_events = Event.passed.order("date DESC")
    end
    
    def new
      @event = Event.new
      @event.author = current_user.email
      new!
    end
    
    def show
      if params[:id] =~ /^\d+/
        @event = Event.find(params[:id])
      else
        @event = Event.find_by_navigation_link(params[:id])
      end
      authorize! :read, @event
      if @event.end_date <= Time.now + 1.day
        @event.archived = 1;
        @event.save
      end
      show!
    end
    
    def edit
      if params[:id] =~ /^\d+/
        @event = Event.find(params[:id])
      else
        @event = Event.find_by_navigation_link(params[:id])
      end
      authorize! :update, @event
      edit!
    end
    
    def update
      if params[:id] =~ /^\d+/
        @event = Event.find(params[:id])
      else
        @event = Event.find_by_navigation_link(params[:id])
      end
      authorize! :update, @event
      update!
    end
    
    def destroy
      if params[:id] =~ /^\d+/
        @event = Event.find(params[:id])
      else
        @event = Event.find_by_navigation_link(params[:id])
      end
      authorize! :destroy, @event
      destroy!
    end
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :navigation_link %>
    <%= f.text_field :navigation_link %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.cktext_area :content, :toolbar => "Easy" %>
  </div>
  <div class="field">
    <%= f.label :published %>
    <%= f.check_box :published %>
  </div>
  <% if (current_user && current_user.role == "editor") %>
  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>
  <% end %>
  <div class="field">
	<%= f.label "Start Date" %>
    <%= f.date_select :date, :start_year => 2010, :order => [:day, :month, :year] %>
  </div>
  <div class="field">
	<%= f.label "End Date" %>
    <%= f.date_select :end_date, :start_year => 2010, :order => [:day, :month, :year] %>
  </div>

  <div class="field">
    <%= f.label :external_link %>
    <%= f.text_field :external_link %>
  </div>
  <div class="field">
    <%= f.label :tags %>
    <%= f.text_field :tags %>
  </div>
  <div class="actions">
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/events/index.html.erb
<% title("Events") %>
<h2>events</h2><div class="actions">
<% if can? :create, Event %>
	<%= link_to "New event", new_event_path %>
<% end %>
</div>
<% @new_events.each do |event| %>
	<% if can? :read, event %>
		<h3>
		<% if event.external_link.blank? %>	
			<%= link_to event.title, event %>
		<% else %>
			<%= link_to event.title, event.external_link, :target => "_blank" %>
		<% end %>
		</h3>
		<div class="actions"><div class="top0">
		<% if can? :update, event %>
			<%= link_to "Edit", edit_event_path(event) %> | 
		<% end %> 
		<% if can? :destroy, event %>
			<%= link_to "Delete", event_path(event), :confirm => "Are you sure you want to delete "+event.title+"?\nThis action cannot be undone!", :method => :delete %>
		<% end %></div></div>
		<p style="margin-top: 0px; margin-bottom: 0px;"><i>on: <%= l(event.date, :format => "%d-%b-%Y") %></i></p>
		<div class="post">
		<%= truncate_html(event.content, :length => 400, :omission => '...') %>
		<% if event.external_link.blank? %>
			<%= link_to "read more", event, :class => "readmore" %> <img src='/images/color_slash.gif'>
		<% else %>
			<%= link_to "read more", event.external_link, :class => "readmore" %> <img src='/images/color_slash.gif'>
		<% end %>
		</div><p/>
	<% end %>
<% end %>
<div id="spacing70"></div>
<h2>archive</h2>
<% @old_events.each do |event| %>
	<% if can? :read, event %>
		<h3>
		<% if event.external_link.blank? %>	
			<%= link_to event.title, event %>
		<% else %>
			<%= link_to event.title, event.external_link, :target => "_blank" %>
		<% end %>
		</h3>
		<div class="actions"><div class="top0">
		<% if can? :update, event %>
			<%= link_to "Edit", edit_event_path(event) %> | 
		<% end %> 
		<% if can? :destroy, event %>
			<%= link_to "Delete", event_path(event), :confirm => "Are you sure you want to delete "+event.title+"?\nThis action cannot be undone!", :method => :delete %>
		<% end %></div></div>
		<p style="margin-top: 0px; margin-bottom: 0px;"><i>on: <%= l(event.date, :format => "%d-%b-%Y") %></i></p>
		<div class="post">
		<%= truncate_html(event.content, :length => 400, :omission => '...') %>
		<% if event.external_link.blank? %>
			<%= link_to "read more", event, :class => "readmore" %> <img src='/images/color_slash.gif'>
		<% else %>
			<%= link_to "read more", event.external_link, :class => "readmore" %> <img src='/images/color_slash.gif'>
		<% end %>
		</div><p/>
	<% end %>
<% end %>

app/views/events/new.html.erb
<h2>New event</h2>
 
<%= render :partial => "form" %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<% title(@event.title) %>
<% content_for :tags do %><%= @event.tags %><% end %>
<h2><%= @event.title %></h2> on <%= l(@event.date, :format => "%d %b %Y") %>
<div class="actions">
<% if can? :update, @event %>
	<%= link_to "Edit", edit_event_path(@event) %> |
<% end %>
<% if can? :destroy, @event %>
	<%= link_to "Delete", @event, :confirm => "Are you sure you want to delete "+@event.title+"?\nThis action cannot be undone!", :method => :delete %>
<% end %>	
</div>
<br/><br/>
<div class="post">
<%= raw @event.content %>
</div>