config/routes.rb
DesignUnited::Application.routes.draw do
  get "passwordreset/create"

  get "passwordreset/edit"

  get "passwordreset/update"

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"

  get "blogpages/index"

  get "home/index"

  get "pages/index"
  
  match "about", :controller => "abouts", :action => "show", :id => "1", :as => "aboutdu"
  match "introduction", :controller => "abouts", :action => "show", :id => "2", :as => "introduction"
  match "mission", :controller => "abouts", :action => "show", :id => "3", :as => "mission"
  match "activities", :controller => "abouts", :action => "show", :id => "4", :as => "activities"
  match "contact", :controller => "abouts", :action => "show", :id => "5", :as => "contact"
  
  root :to => "home#index"
  
  match "/pages" => "pages#index" #for search

  resources :abouts
  resources :profiles, :cases, :events, :users, :sessions, :passwordresets
  resources :blogpages do
    resources :comments
  end
  resources :users do
    member do
      get :activate
    end
  end


  
end

app/models/about.rb
class About < Page
    validates_uniqueness_of :navigation_link
    
    def to_param
      navigation_link
    end
end

app/controllers/abouts_controller.rb
class AboutsController < InheritedResources::Base
  #load_and_authorize_resource

  def show
    if params[:id] =~ /^\d+/
      @about = About.find(params[:id])
    else
      @about = About.find_by_navigation_link(params[:id])
    end
    authorize! :read, @about
    @agenda = Event.present.order("date ASC").limit(3)
    show!
  end
  
  def edit
    if params[:id] =~ /^\d+/
      @about = About.find(params[:id])
    else
      @about = About.find_by_navigation_link(params[:id])
    end
    authorize! :update, @about
    edit!
  end
    
  def update
    if params[:id] =~ /^\d+/
      @about = About.find(params[:id])
    else
      @about = About.find_by_navigation_link(params[:id])
    end
    authorize! :update, @about
    update!
  end      
end

app/views/abouts/_form.html.erb
<%= form_for(@about, :url => about_path(@about.id) ) do |f| %>
  <% if @about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@about.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @about.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :navigation_link %>
    <%= f.text_field :navigation_link %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.cktext_area :content, :toolbar => 'Easy' %>
  </div>
  <div class="field">
    <%= f.check_box :published %>
	<%= f.label :published %>
  </div>
    <% if (current_user && current_user.role == "editor") %>
  <div class="field">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :tags %>
    <%= f.text_field :tags %>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/abouts/edit.html.erb
<%= render 'form' %>

app/views/abouts/show.html.erb
<% title(@about.title) %>
<% content_for :tags do %><%= @about.tags %><% end %>
<% content_for :leftcol do %>
	<div id='leftcontent'>
		<div class='links'>
			<h4>design united /</h4>
			<% if @about.id == 1 %>
				<b>about /</b>
			<% else%>
				<%= link_to "about /", aboutdu_path %>
			<% end %><p>
			<% if @about.id == 2 %>
				<b>introduction /</b>
			<% else%>
				<%= link_to "introduction /", introduction_path %>
			<% end %></p><p>
			<% if @about.id == 3 %>
				<b>mission /</b>
			<% else%>
				<%= link_to "mission /", mission_path %>
			<% end %></p><p>
			<% if @about.id == 4 %>
				<b>activities /</b>
			<% else%>
				<%= link_to "activities /", activities_path %>
			<% end %></p><p>
			<% if @about.id == 5 %>
				<b>contact /</b>
			<% else%>
				<%= link_to "contact /", contact_path %>
			<% end %></p><div id="line"></div>
		</div>
	</div>
<% end %>
<div><h2><%= @about.title %></h2></div>
<div class="actions">
<% if can? :update, @about %>
	<%= link_to "Edit", edit_about_path(@about) %>
<% end %>
</div>
<div class="post">
<%= raw @about.content %>
</div>
<% content_for :rightcol do %>
	<% if @agenda %>
		<div id='events'>
			<h2>events</h2><%= render :partial => "events" %>
		</div>
	<% end %>
<% end %>