config/routes.rb
DesignUnited::Application.routes.draw do
  get "passwordreset/create"

  get "passwordreset/edit"

  get "passwordreset/update"

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"

  get "blogpages/index"

  get "home/index"

  get "pages/index"
  
  match "about", :controller => "abouts", :action => "show", :id => "1", :as => "aboutdu"
  match "introduction", :controller => "abouts", :action => "show", :id => "2", :as => "introduction"
  match "mission", :controller => "abouts", :action => "show", :id => "3", :as => "mission"
  match "activities", :controller => "abouts", :action => "show", :id => "4", :as => "activities"
  match "contact", :controller => "abouts", :action => "show", :id => "5", :as => "contact"
  
  root :to => "home#index"
  
  match "/pages" => "pages#index" #for search

  resources :abouts
  resources :profiles, :cases, :events, :users, :sessions, :passwordresets
  resources :blogpages do
    resources :comments
  end
  resources :users do
    member do
      get :activate
    end
  end


  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
      flash[:alert] = "Access Denied. Please log in."
      redirect_to login_url
    end

def load_related(page)
    search = []
    unless page.tags.blank?
      search = page.tags.split(", ")
    end
    pages = []
    profiles = []
    search.each do |s|
      pages << Page.where("tags LIKE ?", '%'+s+'%')
      profiles << Profile.where("tags LIKE ?", '%'+s+'%')
    end
    @relatedpages = []
    @relatedevents = []
    @relatedprofiles = []
    pages.each do |pa|
      pa.reject! {|p| p==page}
      pa.each do |p|
        if p.type == "Event"
          @relatedevents << p
        else
          @relatedpages << p
        end
      end
    end
    profiles.each do |pr|
      pr.each do |profile|
        @relatedprofiles << profile
      end 
    end    
    @relatedpages.uniq!
    @relatedevents.uniq!
    @relatedprofiles.uniq!
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    unless page_title.blank?
      content_for(:title) {"| " + page_title}
    end
  end

  def truncator(html, length, omission)
    if (html.blank? || html.class != String || (html.index("<p>").blank? || html.index("</p>", html.index("</p>")+4).blank?))
      return truncate_html(html, :length => length, :omission => omission)
    else
      start_tag = html.index("<p>") || 0
      end_tag = html.index("</p>",  html.index("</p>")+4) || html.length # hack to get the 2nd </p>
      return truncate_html(html[start_tag..end_tag+4], :length => length, :omission => omission)
    end
  end
end

app/views/application/_casesmenu.html.erb
<% content_for :leftcol do %>
	<div id='leftcontent'>
	<div class='links'><h4>design united&#160;/</h4>
		<% if @case.blank? %>
			<b>cases&#160;/</b>
		<% else%>
			<%= link_to cases_path do %>
				cases&#160;/
			<% end %>
		<% end %>
		<% @cases.each do |c| %>
			<% if can? :read, c %>
			<p><% if @case && @case.id == c.id %>
				<b><%= c.title %>&#160;/<% unless c.published %>&#160;*<% end %></b>
			<% else%>
				<% if c.published %>
					<%= link_to c do %>
						<%= c.title %>&#160;/
					<% end %>
				<% else %> 
					<%= link_to c do %>
						<%= c.title %>&#160;/&#160;*
					<% end %>
				<% end %>
			<% end %></p><% end %>
		<% end %>
		<div id="line"></div></div>
	</div>
<% end %>

app/views/application/_events.html.erb
<table>
<% months = Array.new %>
<% @agenda.each do |event| %>
	<% if event.published %>
	<% unless months.include?(event.date.month) %>
		<% months << event.date.month %>
		<tr><td class="eventmonth" colspan=2><%= l(event.date, :format => "%B") %></td></tr>
	<% end %>
	<tr><td><%= l(event.date, :format => "%d") %></td>
	<td class="eventtitle">
	<b><%= event.title %></b>
	</td></tr>
	<tr><td/>
	<td>
	<div class="post">
	<%= truncate_html(event.content, :length => 80, :omission => "..") %>
	</div>
		<% unless event.external_link.blank? %>
			<%= link_to "read more", event.external_link, :class => "readmore", :target => "_blank" %>  <img class="readmore" src='/images/color_slash.gif'>
		<% else %>
			<%= link_to "read more", event, :class => "readmore" %>  <img class="readmore" src='/images/color_slash.gif'>
		<% end %></td>
		</tr>
	<% end %>
<% end %>
</table><p>
<%= link_to "more events", events_path, :class => "readmore" %>  <img class="readmore" src='/images/color_slash.gif'></p>

app/views/application/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.cktext_area :content, :toolbar => "Easy" %>
  </div>
  <div class="field">
    <%= f.label :published %><br />
    <%= f.check_box :published %>
  </div>
    <% if (current_user && current_user.role == "editor") %>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit "Save" %>
  </div>
<% end %>

app/views/application/_nav.html.erb
<table class="navmenu">
	<tbody>
		<tr>
			<td class="navlink"><%= link_to "about", aboutdu_path, :class => "navlink" %></td><td/>
			<td class="navlink"><%= link_to "profiles", profiles_path, :class => "navlink" %></td><td/>
			<td class="navlink"><%= link_to "cases", cases_path, :class => "navlink" %></td><td/>
			<td class="navlink"><%= link_to "blog", blogpages_path, :class => "navlink" %></td><td/>
			<td class="navlink"><%= link_to "events", events_path, :class => "navlink" %></td>
		</tr>
	</tbody>
</table>

app/views/application/_relatedpages.html.erb
<% unless @relatedpages.blank? %>
<div class='related'>
	<h2>related pages</h2>
	<table>	
		<% @relatedpages.each do |page| %>
			<tr><td><%= link_to page.title, page %></td></tr>
		<% end %>
	</table>
</div>
<% end %>

app/views/application/_relatedprofiles.html.erb
<% unless @relatedprofiles.blank? %>
<div class='related'>
	<h2>related contacts</h2>
	<% @relatedprofiles.each do |profile| %>
		<p>
		<% unless profile.external_link.blank? %>
			<%= link_to profile.shortname, profile.external_link, :target => "_blank" %>
		<% else %>
			<%= profile.shortname %>
		<% end %>
		<br/>	
		<%= profile.university %><% unless profile.department.blank?%> - <%= profile.department %><%end%>
		</p>
	<% end %>
</div>
<% end %>

app/views/application/_search.html.erb
<% @search = Page.search(params[:search]) %>
<%= form_for @search do |f| %>
   <%= f.text_field :content_contains %>
   <%= f.submit "Search" %>
<% end %>

app/views/application/_sortprof.html.erb
<% content_for :leftcol do %>
	<div id='leftcontent'>
	<div class='links'>
	<h4>Sort by:</h4>
	<p>
	<% if params[:sort]=="firstnamefull ASC" %>
		<%= link_to "First Name", {:controller => "profiles", :action => "index", :sort => "firstnamefull DESC"}%>
	<% else %>
		<%= link_to "First Name", {:controller => "profiles", :action => "index", :sort => "firstnamefull ASC"}%>
	<% end %>
	</p><p>
	<% if params[:sort]=="lastname ASC" %>
		<%= link_to "Last Name", {:controller => "profiles", :action => "index", :sort => "lastname DESC"}%>
	<% else %>
		<%= link_to "Last Name", {:controller => "profiles", :action => "index", :sort => "lastname ASC"}%>
	<% end %>
	</p><p>
	<% if params[:sort]=="university ASC" %>
		<%= link_to "University", {:controller => "profiles", :action => "index", :sort => "university DESC"}%>
	<% else %>
		<%= link_to "University", {:controller => "profiles", :action => "index", :sort => "university ASC"}%>
	<% end %>
	</p><p>
	<% if params[:sort]=="department ASC" %>
		<%= link_to "Chair", {:controller => "profiles", :action => "index", :sort => "department DESC"}%>
	<% else %>
		<%= link_to "Chair", {:controller => "profiles", :action => "index", :sort => "department ASC"}%>
	<% end %>
	</p>
	</div></div>
<% end %>