config/routes.rb
DesignUnited::Application.routes.draw do
  get "passwordreset/create"

  get "passwordreset/edit"

  get "passwordreset/update"

  get "login" => "sessions#new", :as => "login"
  get "logout" => "sessions#destroy", :as => "logout"
  get "signup" => "users#new", :as => "signup"

  get "blogpages/index"

  get "home/index"

  get "pages/index"
  
  match "about", :controller => "abouts", :action => "show", :id => "1", :as => "aboutdu"
  match "introduction", :controller => "abouts", :action => "show", :id => "2", :as => "introduction"
  match "mission", :controller => "abouts", :action => "show", :id => "3", :as => "mission"
  match "activities", :controller => "abouts", :action => "show", :id => "4", :as => "activities"
  match "contact", :controller => "abouts", :action => "show", :id => "5", :as => "contact"
  
  root :to => "home#index"
  
  match "/pages" => "pages#index" #for search

  resources :abouts
  resources :profiles, :cases, :events, :users, :sessions, :passwordresets
  resources :blogpages do
    resources :comments
  end
  resources :users do
    member do
      get :activate
    end
  end


  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="description" content="Design United, platform for Dutch Research in Design’ is a new initiative by the 3TU programs in Industrial Design. ">
<meta name="keywords" content="design, united, innovative, industrial, research, <%= yield :tags %>">
<meta name="author" content="DesignUnited">
<meta name="copyright" content="Copyright 2011-<%=Time.now.year%> Delft University of Techology, University of Twente, Eindhoven University of Technology">
<meta name="robots" content="index, follow">
<meta name="revisit-after" content="7 days">
  <title>Design United <%= yield :title %></title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= javascript_include_tag :ckeditor %>
</head>
<body>
<div id='wrapper'>
<div id='leftcol'>
	<p>
		<div id='DULogo'>
		<%= link_to root_path do %>
			<img src="/images/DUlogo.png" width="160px"/>
		<% end %>
		</div>
	</p>
		<%= yield :leftcol %>
</div>
<div id='midcol'>
	<div id='navigation'>
		<%= render :partial => "nav" %>
	</div>
	<div id='content'>
		<% if notice %>
			<p id="notice"><%= notice %></p>
		<% end %>
		<% if alert %>
			<p id="alert"><%= alert %></p>
		<% end %>
		<%= yield %>
	</div>
</div>
<div id='rightcol'>
	<table id="contact">
        <tbody>
                        <td><%= link_to "contact", contact_path, :class => "navlink" %></td>
        </tbody>
	</table>
	<div id='search'><div class='backgroundtitle'><h4>search /</h4></div>
	<%= render :partial => "search" %>
	</div>
	<div id='login'>
		<div class='backgroundtitle'>
		<% if current_user %>
			<h4>Logged in /</h4></div>
			as  
			<% if current_user.username.blank? %>
				<%= current_user.email %>
			<% else %>
				<%= current_user.username %>
			<% end %>
			<%= link_to "Logout", logout_path %><br/>
			<% if can? :view, User %>
				<div id="manageusers">
				<%= link_to "Manage users", users_path %>
				</div>
			<% end %>
		<% else %>
			<h4><%= link_to "Sign up", signup_path %> or <%= link_to "log in /", login_path %></h4></div>
		<% end %>
	</div>
		<%= yield :rightcol %>
	</div>
</div>
<div class="clearfooter"></div>
</div>
<div id="footercenter">
<div id="footer">
<table>
<tr>
<td><a href="http://www.io.tudelft.nl/" target="_blank"><img src="/images/TU_d_logo_100px.png" width="100px"/></a></td>
<td><a href="http://www.tue.nl/universiteit/kolom-2/faculteiten/industrial-design/" target="_blank"><img src="/images/TUe_logo_100px.png" width="100px"/></a></td>
<td><a href="http://www.utwente.nl/ide/" target="_blank"><img src="/images/UT_logo_100px.png" width="100px"/></a></td>
<td><a href="http://www.agentschapnl.nl/" target="_blank"><img src="/images/AgentNL_logo_100px.png" width="100px"/></a></td>
</tr>
</table></div>
</div>
<script type="text/javascript">
 
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-26637317-1']);
  _gaq.push(['_trackPageview']);
 
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
 
</script>
</body>
</html>